project:
  type: website
  output-dir: docs

website:
  title: "Microeconomics 2 project website"
  navbar:
    title: false
    left:
      - href: ../
        text: My Github Page
      - href: index.qmd
        text: Home 
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



