project:
  type: website
  output-dir: docs

website:
  title: "Microeconomics 2 project website"
  navbar:
    background: '#e0e0e0'
    title: false
    left:
      - href: ../
        text: Home
      - href: index.qmd
        text: Microeconomics project
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/Paulogcd/Micro_project
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



